CREATE OR REPLACE DATABASE spotify_etl_project;

CREATE OR REPLACE STORAGE INTEGRATION spotify_s3_int
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = S3
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '*******'
    STORAGE_ALLOWED_LOCATIONS = ('*****')
     

DESC INTEGRATION spotify_s3_int;
